import Link from "next/link";
import { Award,Bell,CalendarDays,CircleCheck,FileBadge,LogOut,UserRound,UsersRound } from "lucide-react";
import { PublicShell } from "@/components/layout/public-shell";
import { ProfileForm } from "@/features/profile/profile-form";
import { requireUser } from "@/lib/auth/guards";
import { apiFetch } from "@/lib/api/server";
import { signOutAction } from "@/app/login/actions";
export const dynamic="force-dynamic";
function formatDate(value?:string|null){if(!value)return "Date TBA";return new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(value));}
export default async function ProfilePage({searchParams}:{searchParams:Promise<{registered?:string;welcome?:string}>}){const params=await searchParams;const {user}=await requireUser();let data:any={user,registrations:[],certificates:[],notifications:[],teams:[],recognitions:[]};let loadError="";try{data=await apiFetch<any>("/api/profile",{},true);}catch(e){loadError=e instanceof Error?e.message:"Profile data could not be loaded.";}const profile=data.user??user;const registrations=data.registrations??[];const certificates=data.certificates??[];const notifications=data.notifications??[];const teams=data.teams??[];const recognitions=data.recognitions??[];const safeProfile={full_name:profile.fullName??"",mobile:profile.mobile??"",college:profile.college??"",department:profile.department??"",year:profile.year??"",prn_student_id:profile.prnStudentId??"",skills:profile.skills??[],github_url:profile.githubUrl??"",linkedin_url:profile.linkedinUrl??"",email_notifications:profile.emailNotifications??true};return <PublicShell><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 border-b border-white/[0.07] pb-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[var(--accent)]"><UserRound size={15}/>Student Profile</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Hello, {(profile.fullName||"Student").split(" ")[0]} 👋</h1><p className="mt-2 text-sm text-white/45">Your permanent NavVedh record. Archived events remain here as history.</p></div><form action={signOutAction}><button className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm text-white/60"><LogOut size={16}/>Sign out</button></form></div>{params.welcome?<p className="mt-5 rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-200">Account created.</p>:null}{params.registered?<p className="mt-5 rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-200">{params.registered==="already"?"You are already registered for that event.":"Event registration saved."}</p>:null}{loadError?<p className="mt-5 rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{loadError}</p>:null}
<div className="mt-6 grid gap-4 sm:grid-cols-5">{[[CalendarDays,registrations.length,"Activities"],[CircleCheck,registrations.filter((r:any)=>r.attendanceStatus==="attended").length,"Attended"],[UsersRound,teams.length,"Teams"],[Award,recognitions.length,"Badges / Titles"],[FileBadge,certificates.length,"Certificates"]].map(([Icon,value,label]:any)=><div key={label} className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><Icon size={18} className="text-[var(--accent)]"/><div className="mt-4 text-3xl font-semibold">{value}</div><div className="text-sm text-white/40">{label}</div></div>)}</div>
<div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><h2 className="text-xl font-semibold">My Activities & History</h2><div className="mt-5 space-y-3">{registrations.length?registrations.map((r:any)=><div key={r._id} className="rounded-2xl border border-white/[0.06] bg-black/10 p-4"><div className="flex flex-wrap items-center gap-2"><div className="font-medium">{r.event?.name??"Event"}</div>{r.event?.isArchived?<span className="rounded-full border border-amber-400/20 px-2 py-0.5 text-[10px] text-amber-200">History</span>:null}</div><div className="mt-1 text-xs text-white/35">{r.status} · {r.attendanceStatus} · {formatDate(r.registeredAt)}</div>{r.event?.slug&&!r.event?.isArchived?<Link href={`/events/${r.event.slug}`} className="mt-3 inline-block text-xs font-semibold text-[var(--accent)]">View event →</Link>:<div className="mt-3 text-xs text-white/30">This event has been archived, but your participation record is preserved.</div>}</div>):<div className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-white/35">No activity yet.</div>}</div></section><section className="rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Bell size={18} className="text-[var(--accent)]"/><h2 className="text-xl font-semibold">Recent Announcements</h2></div><Link href="/announcements" className="text-xs font-semibold text-[var(--accent)]">View all →</Link></div><div className="mt-5 space-y-3">{notifications.slice(0,3).length?notifications.slice(0,3).map((n:any)=><div key={n._id} className="rounded-2xl border border-white/[0.06] bg-black/10 p-4"><div className="text-sm font-medium">{n.title}</div><p className="mt-1 text-sm leading-6 text-white/45">{n.body}</p></div>):<div className="text-sm text-white/35">No announcements yet.</div>}</div></section></div>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><h2 className="text-xl font-semibold">Achievements, Badges & Titles</h2><div className="mt-5 space-y-3">{recognitions.length?recognitions.map((r:any)=><div key={r._id} className="rounded-2xl border border-[var(--accent)]/15 bg-[var(--accent)]/[0.04] p-4"><div className="flex items-center gap-2"><Award size={16} className="text-[var(--accent)]"/><div className="font-semibold">{r.title}</div><span className="text-[10px] uppercase text-white/35">{r.type}</span></div><div className="mt-1 text-xs text-white/40">{r.event?.name??"NavVedh"}</div>{r.description?<p className="mt-2 text-sm text-white/45">{r.description}</p>:null}</div>):<div className="text-sm text-white/35">No special recognition yet.</div>}</div></section><section className="rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><h2 className="text-xl font-semibold">Certificates</h2><div className="mt-5 space-y-3">{certificates.length?certificates.map((c:any)=><div key={c._id} className="rounded-2xl border border-white/[0.06] bg-black/10 p-4"><div className="text-sm font-medium">{c.event?.name??"Club certificate"}</div><div className="mt-1 text-xs text-white/40">{c.awardName||c.roleType} · {c.certificateNumber}</div><div className="mt-3 flex gap-4"><Link href={`/certificates/${encodeURIComponent(c.certificateNumber)}`} className="text-xs font-semibold text-[var(--accent)]">See Certificate →</Link><Link href={`/verify?id=${encodeURIComponent(c.certificateNumber)}`} className="text-xs text-white/40">Verify →</Link></div></div>):<div className="text-sm text-white/35">No certificates yet.</div>}</div></section></div>
<section className="mt-6 rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><h2 className="text-xl font-semibold">Profile Details</h2><div className="mt-5"><ProfileForm profile={safeProfile}/></div></section></section></PublicShell>}
