import Link from "next/link";
import { Search, UsersRound } from "lucide-react";
import { requireAdmin } from "@/lib/auth/guards";
import { apiFetch } from "@/lib/api/server";
export const dynamic="force-dynamic";
export default async function AdminUsersPage({searchParams}:{searchParams:Promise<{q?:string;year?:string;college?:string;department?:string}>}){
  await requireAdmin(); const p=await searchParams; const qs=new URLSearchParams(); for(const [k,v] of Object.entries(p))if(v)qs.set(k,v);
  let users:any[]=[];let error="";try{({users}=await apiFetch<any>(`/api/admin/users?${qs.toString()}`,{},true));}catch(e){error=e instanceof Error?e.message:"Users could not be loaded.";}
  return <main className="p-4 sm:p-6 lg:p-8"><div className="border-b border-white/[0.07] pb-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[var(--accent)]"><UsersRound size={15}/>Users & profiles</div><h1 className="mt-3 text-3xl font-semibold">Registered students</h1></div>{error?<p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>:null}<form className="mt-6 grid gap-3 lg:grid-cols-[1fr_180px_220px_220px_auto]"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/30"/><input name="q" defaultValue={p.q??""} placeholder="Search name, email, college…" className="min-h-11 w-full rounded-xl border border-white/10 bg-black/20 pl-10 pr-3 text-sm"/></label><input name="year" defaultValue={p.year??""} placeholder="Year" className="min-h-11 rounded-xl border border-white/10 bg-black/20 px-3 text-sm"/><input name="college" defaultValue={p.college??""} placeholder="College" className="min-h-11 rounded-xl border border-white/10 bg-black/20 px-3 text-sm"/><input name="department" defaultValue={p.department??""} placeholder="Department" className="min-h-11 rounded-xl border border-white/10 bg-black/20 px-3 text-sm"/><button className="min-h-11 rounded-xl bg-white/[0.07] px-4 text-sm font-semibold">Filter</button></form><div className="mt-5 overflow-x-auto rounded-2xl border border-white/[0.08]"><table className="min-w-full text-left text-sm"><thead className="bg-white/[0.035] text-xs uppercase tracking-wide text-white/35"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Year</th><th className="px-4 py-3">College</th><th className="px-4 py-3">Roles</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/[0.06]"><td className="px-4 py-3"><div className="font-medium">{u.fullName}</div><div className="text-xs text-white/35">{u.email}</div></td><td className="px-4 py-3 text-white/50">{u.year||"—"}</td><td className="px-4 py-3 text-white/50">{u.college||"—"}</td><td className="px-4 py-3 text-white/50">{u.roles?.join(", ")}</td><td className="px-4 py-3"><Link href={`/admin/users/${u.id}`} className="font-semibold text-[var(--accent)]">Manage →</Link></td></tr>)}</tbody></table>{!users.length&&!error?<div className="p-8 text-center text-sm text-white/35">No users found.</div>:null}</div></main>;
}
