"use client";
import Link from "next/link";
import { Bell, LayoutDashboard, LogIn, Menu, UserPlus, UserRound, X } from "lucide-react";
import { useState } from "react";
import { primaryNav, siteConfig } from "@/config/site";
import { ButtonLink } from "@/components/ui/button-link";
import type { ClubUser } from "@/lib/auth/guards";

export function Navbar({ user }: { user: ClubUser | null }) {
  const [open,setOpen]=useState(false);
  const isAdmin=Boolean(user?.roles.some((r)=>r==="ADMIN"||r==="SUPER_ADMIN"));
  const isFaculty=Boolean(user?.roles.some((r)=>r==="FACULTY"||r==="SUPER_ADMIN"));
  return <header className="sticky top-0 z-50 border-b border-white/[0.06] bg-[rgba(7,10,15,0.82)] backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" onClick={()=>setOpen(false)} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-[var(--accent)]/30 bg-[var(--accent)]/10 font-mono text-xs font-bold text-[var(--accent)]">CSE</span><div><div className="text-sm font-semibold">{siteConfig.clubName}</div><div className="hidden text-[11px] text-white/42 sm:block">AITRC · CSE</div></div></Link><nav className="hidden items-center gap-1 xl:flex">{primaryNav.map((item)=><Link key={item.href} href={item.href} className="rounded-lg px-3 py-2 text-sm text-white/62 hover:bg-white/[0.045] hover:text-white">{item.label}</Link>)}</nav><div className="hidden items-center gap-1 xl:flex">{user?<><ButtonLink href="/announcements" variant="ghost"><Bell size={16} className="mr-2"/>Announcements</ButtonLink><ButtonLink href="/profile" variant="ghost"><UserRound size={16} className="mr-2"/>Profile</ButtonLink>{isFaculty?<ButtonLink href="/faculty" variant="secondary">Faculty</ButtonLink>:null}{isAdmin?<ButtonLink href="/admin"><LayoutDashboard size={16} className="mr-2"/>Admin</ButtonLink>:null}</>:<><ButtonLink href="/login" variant="ghost"><LogIn size={16} className="mr-2"/>Sign In</ButtonLink><ButtonLink href="/register"><UserPlus size={16} className="mr-2"/>Register</ButtonLink></>}</div><button type="button" className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 xl:hidden" onClick={()=>setOpen(v=>!v)}>{open?<X size={20}/>:<Menu size={20}/>}</button></div>{open?<div className="border-t border-white/[0.06] bg-[#090c12] px-4 py-4 xl:hidden"><nav className="mx-auto grid max-w-7xl gap-1">{primaryNav.map((item)=><Link key={item.href} href={item.href} onClick={()=>setOpen(false)} className="rounded-xl px-3 py-3 text-sm text-white/70">{item.label}</Link>)}<div className="mt-3 grid gap-2 border-t border-white/[0.06] pt-4">{user?<><Link href="/announcements" onClick={()=>setOpen(false)} className="rounded-xl border border-white/10 p-3 text-center text-sm">Announcements</Link><Link href="/profile" onClick={()=>setOpen(false)} className="rounded-xl border border-white/10 p-3 text-center text-sm">My Profile</Link>{isFaculty?<Link href="/faculty" onClick={()=>setOpen(false)} className="rounded-xl border border-white/10 p-3 text-center text-sm">Faculty Dashboard</Link>:null}{isAdmin?<Link href="/admin" onClick={()=>setOpen(false)} className="rounded-xl bg-[var(--accent)] p-3 text-center text-sm font-bold text-[#07111f]">Admin Dashboard</Link>:null}</>:<><Link href="/login" className="rounded-xl border border-white/10 p-3 text-center text-sm">Sign In</Link><Link href="/register" className="rounded-xl bg-[var(--accent)] p-3 text-center text-sm font-bold text-[#07111f]">Register</Link></>}</div></nav></div>:null}</header>;
}
