import Link from "next/link";
import { Bell,CheckCheck } from "lucide-react";
import { PublicShell } from "@/components/layout/public-shell";
import { requireUser } from "@/lib/auth/guards";
import { apiFetch } from "@/lib/api/server";
import { markAllAnnouncementsReadAction,markAnnouncementReadAction } from "./actions";
export const dynamic="force-dynamic";
function date(v?:string){return v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"";}
export default async function Page(){await requireUser("/announcements");const data=await apiFetch<any>("/api/announcements",{},true);return <PublicShell><section className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 border-b border-white/[0.07] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[var(--accent)]"><Bell size={16}/>Student Updates</div><h1 className="mt-3 text-3xl font-semibold">Announcements</h1></div>{data.unreadCount?<form action={markAllAnnouncementsReadAction}><button className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm"><CheckCheck size={16}/>Mark all read</button></form>:null}</div><div className="mt-6 space-y-3">{data.notifications.length?data.notifications.map((n:any)=><article key={n._id} className={`rounded-2xl border p-5 ${n.readAt?"border-white/[0.07] bg-white/[0.02]":"border-[var(--accent)]/20 bg-[var(--accent)]/5"}`}><div className="font-semibold">{n.title}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/50">{n.body}</p><div className="mt-3 flex flex-wrap items-center gap-4 text-xs"><span className="text-white/30">{date(n.createdAt)}</span>{n.link?<Link href={n.link} className="font-semibold text-[var(--accent)]">Open →</Link>:null}{!n.readAt?<form action={markAnnouncementReadAction}><input type="hidden" name="id" value={n._id}/><button className="text-white/50">Mark read</button></form>:null}</div></article>):<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-white/35">No announcements yet.</div>}</div></section></PublicShell>}
