import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicShell } from "@/components/layout/public-shell";
import { requireUser } from "@/lib/auth/guards";
import { apiFetch } from "@/lib/api/server";
import { createTeamAction,joinTeamAction,confirmTeamAction,selectProblemAction,saveSubmissionAction } from "./actions";

export const dynamic="force-dynamic";
const input="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#0b0f16] px-3 text-sm text-white outline-none focus:border-[var(--accent)]";

export default async function HackathonWorkspace({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{error?:string;saved?:string}>}){
  const {slug}=await params;const notice=await searchParams;await requireUser(`/hackathons/${slug}`);
  let event:any;try{({event}=await apiFetch<any>(`/api/events/${slug}`));}catch{return notFound();}
  let workspace:any={registration:null,team:null,problems:[],submission:null};let loadError="";
  try{workspace=await apiFetch<any>(`/api/hackathons/${event._id}/workspace`,{},true);}catch(e){loadError=e instanceof Error?e.message:"Workspace could not be loaded.";}
  const team=workspace.team;const leaderId=team?.leader?String(team.leader):"";const members=(team?.members??[]) as any[];const me=members.find(m=>m.user?._id);const isLeader=Boolean(me&&String(me.user._id)===leaderId);
  return <PublicShell><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="border-b border-white/[0.07] pb-6"><div className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--accent)]">Hackathon workspace</div><h1 className="mt-3 text-3xl font-semibold">{event.name}</h1><p className="mt-2 text-sm text-white/40">Registration → team → problem → project submission.</p></div>
  {notice.error?<p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{notice.error}</p>:null}{notice.saved?<p className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">Saved: {notice.saved.replaceAll("-"," ")}</p>:null}{loadError?<p className="mt-5 text-red-300">{loadError}</p>:null}
  {!workspace.registration?<section className="mt-6 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-5"><h2 className="font-semibold">Register first</h2><p className="mt-2 text-sm text-white/50">You must register for the event before joining the hackathon workspace.</p><Link href={`/events/${slug}`} className="mt-4 inline-block font-semibold text-[var(--accent)]">Open event page →</Link></section>:null}
  {workspace.registration&&!team?<div className="mt-6 grid gap-6 lg:grid-cols-2"><form action={createTeamAction} className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="eventId" value={event._id}/><h2 className="text-xl font-semibold">Create team</h2><label className="mt-4 block text-sm text-white/55">Team name<input name="name" required minLength={2} className={input}/></label><button className="mt-4 min-h-11 rounded-xl bg-[var(--accent)] px-5 text-sm font-bold text-[#07111f]">Create team</button></form><form action={joinTeamAction} className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="eventId" value={event._id}/><h2 className="text-xl font-semibold">Join team</h2><label className="mt-4 block text-sm text-white/55">Invite code<input name="inviteCode" required className={input}/></label><button className="mt-4 min-h-11 rounded-xl border border-white/10 px-5 text-sm font-semibold">Join team</button></form></div>:null}
  {team?<><section className="mt-6 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Team: {team.name}</h2><p className="mt-1 text-sm text-white/40">Status: {team.status} · Invite hint: ***{team.inviteCodeHint}</p></div>{isLeader&&team.status==="forming"?<form action={confirmTeamAction}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="eventId" value={event._id}/><input type="hidden" name="teamId" value={team._id}/><button className="min-h-10 rounded-xl bg-[var(--accent)] px-4 text-sm font-bold text-[#07111f]">Confirm roster</button></form>:null}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{members.map(m=><div key={m.user?._id} className="rounded-xl border border-white/[0.06] p-3"><div className="text-sm font-medium">{m.user?.fullName}</div><div className="mt-1 text-xs text-white/35">{m.role} · {m.user?.email}</div></div>)}</div></section>
  <section className="mt-6 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><h2 className="text-xl font-semibold">Problem statement</h2>{team.problem?<div className="mt-4 rounded-xl border border-[var(--accent)]/20 bg-[var(--accent)]/5 p-4"><div className="text-xs font-bold text-[var(--accent)]">{team.problem.problemId} · {team.problem.domain}</div><div className="mt-1 font-semibold">{team.problem.title}</div><p className="mt-2 text-sm text-white/45">{team.problem.description}</p></div>:isLeader?<form action={selectProblemAction} className="mt-4"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="eventId" value={event._id}/><input type="hidden" name="teamId" value={team._id}/><select name="problemId" required className={input}><option value="">Select problem</option>{workspace.problems.map((p:any)=><option key={p._id} value={p._id}>{p.problemId} — {p.title}</option>)}</select><button className="mt-3 min-h-10 rounded-xl border border-white/10 px-4 text-sm">Select problem</button></form>:<p className="mt-3 text-sm text-white/40">Team leader will choose the problem statement.</p>}</section>
  <form action={saveSubmissionAction} className="mt-6 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="eventId" value={event._id}/><input type="hidden" name="teamId" value={team._id}/><h2 className="text-xl font-semibold">Project submission</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm text-white/55 sm:col-span-2">Project title<input name="projectTitle" required defaultValue={workspace.submission?.projectTitle??""} className={input}/></label><label className="text-sm text-white/55 sm:col-span-2">Short description<textarea name="shortDescription" rows={2} defaultValue={workspace.submission?.shortDescription??""} className={`${input} py-3`}/></label><label className="text-sm text-white/55 sm:col-span-2">Detailed description<textarea name="detailedDescription" rows={5} defaultValue={workspace.submission?.detailedDescription??""} className={`${input} py-3`}/></label><label className="text-sm text-white/55">GitHub URL<input name="githubUrl" defaultValue={workspace.submission?.githubUrl??""} className={input}/></label><label className="text-sm text-white/55">Live demo URL<input name="liveDemoUrl" defaultValue={workspace.submission?.liveDemoUrl??""} className={input}/></label><label className="text-sm text-white/55">Video demo URL<input name="videoDemoUrl" defaultValue={workspace.submission?.videoDemoUrl??""} className={input}/></label><label className="text-sm text-white/55">Pitch deck URL<input name="pitchDeckUrl" defaultValue={workspace.submission?.pitchDeckUrl??""} className={input}/></label><label className="text-sm text-white/55 sm:col-span-2">Technology stack<input name="technologyStack" defaultValue={(workspace.submission?.technologyStack??[]).join(", ")} className={input}/></label></div>{workspace.submission?.status==="final"?<p className="mt-4 text-sm text-emerald-300">Final submission is locked.</p>:<div className="mt-5 flex flex-wrap gap-3"><button name="finalize" value="0" className="min-h-11 rounded-xl border border-white/10 px-5 text-sm font-semibold">Save draft</button><button name="finalize" value="1" className="min-h-11 rounded-xl bg-[var(--accent)] px-5 text-sm font-bold text-[#07111f]">Final submit & lock</button></div>}</form></>:null}
  </main></PublicShell>}
